site_name: Sequelize | The Node.js / io.js ORM for PostgreSQL, MySQL, SQLite and MSSQL
site_description: Sequelize is an ORM for Node.js and io.js. It supports the dialects PostgreSQL, MySQL, MariaDB, SQLite and MSSQL.
repo_url: https://github.com/sequelize/sequelize
site_favicon: favicon.ico
site_url: http://docs.sequelizejs.com
markdown_extensions: [gfm]
theme: readthedocs
extra_css:
- css/custom.css
extra_javascript:
- //cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js
pages:
- Home: 'index.md'
- Documentation:
  - 'Getting Started': 'docs/getting-started.md'
  - 'Working with table schemas': 'docs/schema.md'
  - Models:
    - 'Definition': 'docs/models-definition.md'
    - 'Usage': 'docs/models-usage.md'
  - 'Querying': 'docs/querying.md'
  - 'Scopes': 'docs/scopes.md'
  - 'Instances': 'docs/instances.md'
  - 'Relations / Associations': 'docs/associations.md'
  - 'Hooks': 'docs/hooks.md'
  - 'Transactions': 'docs/transactions.md'
  - 'Working with legacy tables': 'docs/legacy.md'
  - 'Raw queries': 'docs/raw-queries.md'
  - 'Migrations': 'docs/migrations.md'
- API:
  - 'Sequelize': 'api/sequelize.md'
  - 'Model': 'api/model.md'
  - 'Instance': 'api/instance.md'
  - Associations:
    - Overview: 'api/associations/index.md'
    - 'BelongsTo (1:1)': 'api/associations/belongs-to.md'
    - 'HasOne (1:1)': 'api/associations/has-one.md'
    - 'HasMany (1:m)': 'api/associations/has-many.md'
    - 'BelongsToMany (n:m)': 'api/associations/belongs-to-many.md'
  - 'Hooks': 'api/hooks.md'
  - 'Transaction': 'api/transaction.md'
  - 'Datatypes': 'api/datatypes.md'
  - 'Deferrable': 'api/deferrable.md'
  - 'Errors': 'api/errors.md'
- Misc:
  - 'Changelog': 'changelog.md'
  - 'Imprint': 'imprint.md'
