services:
  mysql-80:
    container_name: sequelize-mysql-80
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sequelize_test
      MYSQL_USER: sequelize_test
      MYSQL_PASSWORD: sequelize_test
      MYSQL_ROOT_PASSWORD: sequelize_test
    ports:
      - 20057:3306
    # tmpfs: /var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "-usequelize_test", "-psequelize_test", "status"]
      interval: 3s
      timeout: 1s
      retries: 10

networks:
  default:
    name: sequelize-mysql-80-network
