services:
  mysql-latest:
    container_name: sequelize-mysql-latest
    image: mysql:8.4.7
    environment:
      MYSQL_DATABASE: sequelize_test
      MYSQL_USER: sequelize_test
      MYSQL_PASSWORD: sequelize_test
      MYSQL_ROOT_PASSWORD: sequelize_test
    ports:
      - 20057:3306
    volumes:
      - mysql-latest:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', '-usequelize_test', '-psequelize_test', 'status']
      interval: 3s
      timeout: 1s
      retries: 10

networks:
  default:
    name: sequelize-mysql-latest-network

volumes:
  mysql-latest:
    name: sequelize-mysql-latest-volume
