services:
  mariadb-latest:
    container_name: sequelize-mariadb-latest
    image: mariadb:10.9.4
    environment:
      MYSQL_DATABASE: sequelize_test
      MYSQL_USER: sequelize_test
      MYSQL_PASSWORD: sequelize_test
      MYSQL_ROOT_PASSWORD: sequelize_test
    ports:
      - 21103:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "-usequelize_test", "-psequelize_test", "status"]
      interval: 3s
      timeout: 1s
      retries: 10

networks:
  default:
    name: sequelize-mariadb-latest-network
