name: 'authors update'
on:
  schedule:
    # Run once a week at 00:05 AM UTC on Sunday.
    - cron: '5 0 * * 0'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  authors_update:
    permissions:
      contents: write # for gr2m/create-or-update-pull-request-action to push local changes
      pull-requests: write # for gr2m/create-or-update-pull-request-action to create a PR
    if: github.repository == 'sequelize/sequelize'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: '0' # This is required to actually get all the authors
          persist-credentials: false
      - run: 'dev/update-authors.js' # Run the AUTHORS tool
      - uses: gr2m/create-or-update-pull-request-action@b65137ca591da0b9f43bad7b24df13050ea45d1b # Create a PR or update the Action's existing PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author: SequelizeJS <mail@sequelizejs.com>
          body: >
            Here are some new additions to the AUTHORS file.
            This is an automatically generated PR by the
            `authors.yml` GitHub Action, which runs `dev/update-authors.js`.
          branch: 'actions/authors-update' # Custom branch *just* for this Action.
          commit-message: 'meta: update sequelize AUTHORS'
          labels: meta
          title: 'meta: update sequelize AUTHORS'
